server.port=8082

spring.application.name=categoriameme
spring.cloud.zookeeper.discovery.enabled=true
logging.level.org.apache.zookeeper.ClientCnxn=WARN
spring.main.allow-circular-references=true

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_categoriasmeme
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
